config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users do
    member do
      get :followings
      get :followers
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :content, presence: true
  
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  
  has_many :entries, dependent: :destroy
  has_many :users, through: :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  attachment :profile_image # ここを追加（_idは含めない）
  
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow, dependent: :destroy
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverses_of_relationship, source: :user, dependent: :destroy
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_followings = user.followings.count
    @count_followers = user.followers.count
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # def create
  #   if Entry.where(user_id: current_user.id, room_id: params[:message][:room_id]).present?
  #     @message = Message.create(params.require(:message).permit(:user_id, :content, :room_id).merge(user_id: current_user.id))
  #     redirect_to "/rooms/#{@message.room_id}"
  #   else
  #     flash.now[:danger] = 'メッセージの送信に失敗しました。'
  #     redirect_back(fallback_location: root_path)
  #   end
  # end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'ユーザをフォローしました。'
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'ユーザのフォローを解除しました。'
    redirect_to user
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      # @messages = @room.messages.order(id: :desc).page(params[:page]).per(10)
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update, :destroy, :followings, :followers]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(9)
  end

  def show
    @user = User.find(params[:id])
    counts(@user)
    
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:success] = 'ユーザの更新に成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @user =  User.find(params[:id])
    @user.destroy
    flash[:success] = 'ユーザは正常に削除されました。'
    redirect_to root_url
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :address, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if @current_user
      return @current_user
    else
      @current_user = User.find_by(id: session[:user_id])
      return @current_user
    end
  end

  def logged_in?
    if current_user
      return true
    else
      return false
    end
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> mb-0"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-light font-weight-bold">
    <a class="navbar-brand" href="/">Connect</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'ユーザ', users_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'マイページ', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Connect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <div class="top">
      <%= render 'layouts/navbar' %>
  
      <div class="container p-0">
        <%= render 'layouts/flash_messages' %>

        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="row m-4">
  <div class="col-2 offset-sm-4 col-sm-1 p-0">
    <figure>
      <%= link_to user_path(message.user) do %>
       <%= attachment_image_tag message.user, :profile_image, :fill, 1000, 1000,fallback: "no-image.png", class: "profile_image" %>
      <% end %>
    </figure>
  </div>
  <div class="col-10 col-sm-7 h5 pt-2 pr-0">
    <div>
      <span class=""><%= message.content %></span>
    </div>
    <div class="update text-right pt-1">
      <time><%= message.updated_at.strftime("%Y-%m-%d %H:%M") %></time>投稿
    </div>
  </div>
</div>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), local: true, method: :delete) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'アンフォロー', class: 'btn btn-danger btn-sm' %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.relationships.build, local: true) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォロー', class: 'btn btn-primary btn-sm' %>
    <% end %>
  <% end %>
<% end %>

app/views/rooms/show.html.erb
<div class="overflowh pl-3 pr-3">
<!--スクロールバーを隠す為。-->
  <div class="chatroom m-5" id="target">
    <h1>Chat room</h1>
  </div>
  
  <div class="row">
    <% @entries.each do |e| %>
      <div class="col-sm-6 pl-3 pr-3">
        <div class="card mb-3">
          
          <div id="target" class="user_name row">
            <!--<strong>-->
              <div id="" class="offset-2 col-8 offset-sm-0 col-sm-5 text-center p-0" >
                <figure class="image">
                  <%= link_to user_path(e.user) do %>
                    <%= attachment_image_tag e.user, :profile_image, :fill, 1000, 1000,fallback: "no-image.png", class: "profile_image" %>
                  <% end %>
                </figure>
              </div>
              <div class="col-sm-6 p-0">
                <div class="card_body">
                  <div class="mt-1 mb-3 h4">
                    <a class="rooms-user-link" href="/users/<%= e.user.id %>">
                      <%= e.user.name %> さん
                    </a>
                  </div>
                  <div class="mb-3"><%= e.user.address %></div>
                  <div class="mb-3"><%= e.user.profile %></div>
                </div>
              </div>
            <!--</strong>-->
          </div>
        </div>
      </div>
    <% end %>
  </div>
  
  
  <hr class="mb-5">
  
  
  <div id="messages" class="" data-room_id="<%= @room.id %>">
    <!--<ul class="list-group">-->
      <%= render @messages %>
    <!--</ul>-->
  </div>
  <!--<div class="pagination justify-content-end p-3">-->
    <!--<p>< paginate @messages ></p>-->
  <!--</div>-->
  
  <form class="">
    <div class="form-group row posts mb-5 mr-0">
      <div class="offset-sm-4 col-sm-6 mb-1 pr-0">
        <input type="text" id="chat-input" class="form-control" data-behavior="room_speaker">
      </div>
      <div class="col-sm-2 text-right text-sm-left pr-0">
        <button id="button" type="submit" class="btn btn-primary btn-sm m-1">送信</button>
      </div>
    </div>
  </form>
</div>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Connect!</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <div class="row">
    <% users.each do |user| %>
    <div class="col-sm-4 mb-4">
      <div class="card text-center">
        <div class="card-img-top">
          <figure class="pt-3">
            <%= link_to user_path(user) do %>
              <%= attachment_image_tag user, :profile_image, :fill, 1000, 1000, fallback: "no-image.png", class: "profile_image" %>
            <% end %>
          </figure>
        </div>
        <div class="card_body mb-3">
          <div><h3><%= link_to user.name, user_path(user) %></h3></div>
          <div>
            投稿数：<span><%= user.messages.count %></span>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="overflowh">
<!--スクロールバーを隠す為。-->
  <div class="text-center mt-4">
    <h1>ユーザ編集</h1>
  </div>
  
  <div class="row pl-3 pr-3 mb-4">
    <div class="col-sm-6 offset-sm-3">
  
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        
        <div class="form-group">
          <%= f.label :name, '名前' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :address, '所在' %>
          <%= f.text_field :address, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :profile, 'プロフィール' %>
          <%= f.text_area :profile, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :profile_image, 'プロフィール画像' %>
          <%= f.attachment_field :profile_image, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :email, 'メールアドレス' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :password, 'パスワード' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :password_confirmation, 'パスワード確認' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
  
        <%= f.submit '編 集', class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="text-center m-5">
  <h1>フォロワー一覧</h1>
</div>

<div class="pl-3 pr-3">
  <%= render 'users', users: @followers %>
</div>

app/views/users/followings.html.erb
<div class="text-center m-5">
  <h1>フォロー一覧</h1>
</div>

<div class="pl-3 pr-3">
  <%= render 'users', users: @followings %>
</div>

app/views/users/index.html.erb
<div class="text-center m-5">
  <h1>ユーザ一覧</h1>
</div>

<div class="pl-3 pr-3">
  <%= render 'users', users: @users %>
</div>

app/views/users/new.html.erb
<div class="overflowh">
<!--スクロールバーを隠す為。-->
  <div class="text-center mt-4">
    <h1>新規登録</h1>
  </div>
  
  <div class="row pl-3 pr-3 mb-4">
    <div class="col-sm-6 offset-sm-3">
  
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        
        <div class="form-group">
          <%= f.label :name, '名前' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :email, 'メールアドレス' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :password, 'パスワード' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :password_confirmation, 'パスワード確認' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
  
        <%= f.submit '登 録', class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="video_container">
  <%= video_tag "/assets/videos/video04.mp4", class: "video_tag", loop: true, autoplay: true, muted: true, width: "100%", height: "100%" %>
</div>

<div class="video_sidebar">
  <!--flashにメッセージが入っていれば、pt-5を追加。-->
  <% if flash[:success] %>
    <div class="pt-5"></div>
  <% end %>
  
  <div class="text-center m-5 pt-5">
    <h1>マイページ</h1>
  </div>
  
  <!--<section class="section">-->
    <div class="row">
      <div class="offset-2 col-8 offset-sm-1 col-sm-2 text-center">
        <!--<div id="target">-->
          <figure>
            <%= attachment_image_tag @user, :profile_image, :fill, 1000, 1000,fallback: "no-image.png", class: "profile_image" %>
          </figure>
        <!--</div>-->
      </div>
      <div class="col-sm-4 mb-3" id="target">
        <div class="mb-3 h4"><%= @user.name %></div>
        <div class="h5 mb-3">
          <% if @user.id == current_user.id %>
            <%= @user.email %>
          <% end %>
        </div>
        <div class="mb-3"><%= @user.address %></div>
        <div><%= @user.profile %></div>
      </div>
      <div class="col-sm-4">
        <div id="target">
          <div id="target1" class="d-flex flex-row mb-4">
            <% if @user.id == current_user.id %>
              <%= link_to edit_user_path(@user), class: "btn btn-primary btn-sm mr-4" do %>
                <span>
                  <i class="fas fa-user faa-bounce animated-hover"></i>
                </span>
                編集
              <% end %>
              <%= link_to user_path(@user), method: :delete, data: { confirm: "本当にユーザ登録を解除してもよろしいですか?" }, class: "btn btn-danger btn-sm" do %>
                <span>
                  <i class="fas fa-user faa-wrench animated-hover" aria-hidden="true"></i>
                </span>
                削除
              <% end %>
            <% end %>
            <div>
              <%= render 'relationships/follow_button', user: @user %>
            </div>
          </div>
          <div id="target1" class="d-flex flex-row mb-4">
            <%= link_to followings_user_path(@user), class: "btn btn-primary btn-sm mr-4" do %>
              フォロー中
              <span class="badge badge-success">
                <%= @count_followings %>
              </span>
            <% end %>
            <%= link_to followers_user_path(@user), class: "btn btn-primary btn-sm" do %>
              フォロワー
              <span class="badge badge-secondary">
                <%= @count_followers %>
              </span>
            <% end %>
          </div>
          <div id="target1">
            <% unless @user.id == current_user.id %>
              <% if current_user.following?(@user) && @user.following?(current_user) %>
                <% if @isRoom == true %>
                  <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-sm">チャットへ</a></p>
                <% else %>
                  <%= form_for @room do |f| %>
                    <%= fields_for @entry do |e| %>
                      <%= e.hidden_field :user_id, value: @user.id %>
                    <% end %>
                    <%= f.submit "チャットを始める", class: "btn btn-primary btn-sm user-show-chat" %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
  
    </div>
  <!--</section>-->
</div>